export const ALL_FORMATS = [
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/031d0b25-5ce6-4c27-8e82-d33ec3b0b178.png',
    icon: 'Landmark',
    title: 'Классические мастер-классы',
    place: 'В студии',
    duration: '1 час',
    people: '1–20',
    peopleMin: 1,
    peopleMax: 20,
    age: '3+',
    ageMin: 3,
    days: 'Любой день',
    daysKey: 'any',
    price: 'от 1 500 ₽',
    priceKey: 'fixed',
    location: 'studio',
    durationKey: '1h',
    desc: 'Классические мастер-классы — это отдельные занятия по одной из четырёх техник на выбор: лепка из глины, гончарный круг, роспись ангобами или роспись акрилом. Всё включено, готовое изделие выдаётся после обжига.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight', action: 'link', to: '/workshops' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/cd92a426-9a1e-4eba-81fa-09e5b75b623d.jpg',
    icon: 'Baby',
    title: 'Детская группа (сб/вс)',
    place: 'В студии',
    duration: '1 час',
    people: '1–20',
    peopleMin: 1,
    peopleMax: 20,
    age: '3–10 лет',
    ageMin: 3,
    days: 'Сб / Вс',
    daysKey: 'weekend',
    price: '1 900 ₽',
    priceKey: 'fixed',
    location: 'studio',
    durationKey: '1h',
    desc: 'Детский мастер-класс выходного дня по субботам и воскресеньям. Состоит из двух этапов: сначала лепка за столом, через две недели — роспись готовых изделий или утиля. Готовое изделие забирают через две недели после росписи.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight', action: 'kids' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/031d0b25-5ce6-4c27-8e82-d33ec3b0b178.png',
    icon: 'Rocket',
    title: 'Промо-группа (пн–пт)',
    place: 'В студии',
    duration: '1 час',
    people: '10–12',
    peopleMin: 10,
    peopleMax: 12,
    age: '7+',
    ageMin: 7,
    days: 'Пн – Пт',
    daysKey: 'weekday',
    price: '2 000 ₽',
    priceKey: 'fixed',
    location: 'studio',
    durationKey: '1h',
    desc: 'Детские будничные группы по тарифу промо для групп от 10 до 30 человек. Чем больше групп и человек, тем дешевле стоимость. Скидки до 50% от первоначальной цены.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight', action: 'promo' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/0bce1c46-ce6d-45d4-9a78-fc97b423975d.jpg',
    icon: 'UtensilsCrossed',
    title: 'Тематические мастер-классы',
    place: 'В студии',
    duration: '6,5 ч',
    people: '1–3',
    peopleMin: 1,
    peopleMax: 3,
    age: '12+',
    ageMin: 12,
    days: 'Любой день',
    daysKey: 'any',
    price: '5 000–9 000 ₽',
    priceKey: 'fixed',
    location: 'studio',
    durationKey: '6h',
    desc: 'Тематические мастер-классы — это занятия по созданию конкретного изделия (блюдо, маслёнка, гномы, грибы, изразцы, пуровер и др.) с использованием лепки, гончарного круга или росписи. Всё включено, готовое изделие после обжига.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/0691624f-cc62-4d3b-8069-e5ab1d935b18.png',
    icon: 'Heart',
    title: 'Свидание в мастерской',
    place: 'В студии',
    duration: '1,5 часа',
    people: '2',
    peopleMin: 2,
    peopleMax: 2,
    age: '3+',
    ageMin: 3,
    days: 'Любой день',
    daysKey: 'any',
    price: '7 000 ₽',
    priceKey: 'fixed',
    location: 'studio',
    durationKey: 'negotiable',
    desc: '«Свидание в мастерской» — это романтический мастер-класс для двоих за одним гончарным кругом. За 1,5 часа вы создаёте и сразу расписываете уникальное изделие под руководством мастера. Всё включено, готовую работу забираете через 3 недели.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/42ebb68f-5d36-4a32-b4bd-b871307db9bc.jpg',
    icon: 'Armchair',
    title: 'Коворкинг',
    place: 'В студии',
    duration: 'от 1 часа',
    people: 'от 1',
    peopleMin: 1,
    peopleMax: 100,
    age: '3+',
    ageMin: 3,
    days: 'Любой день',
    daysKey: 'any',
    price: 'Индивидуально',
    priceKey: 'negotiable',
    location: 'studio',
    durationKey: 'negotiable',
    desc: 'Коворкинг — это аренда рабочего места в мастерской на ВДНХ для самостоятельной работы с глиной. Доступны гончарный круг (700 ₽/час), лепка (500 ₽/час) и роспись ангобами (500 ₽/час). Глина и обжиг оплачиваются отдельно. Роспись глазурями не входит. Для участников любого возраста, ежедневно с 11:00 до 20:00. Обязательна предварительная запись.',
    cta: { label: 'Выбрать услугу', variant: 'default' as const, icon: 'ChevronRight' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/7898283f-b258-43b1-ae5e-b5d2e1c4b1f7.jpg',
    icon: 'PartyPopper',
    title: 'Мероприятия (ДР, корп, девичник)',
    place: 'В студии или выезд',
    duration: 'Индивидуально',
    people: 'Любое',
    peopleMin: 1,
    peopleMax: 100,
    age: '3+',
    ageMin: 3,
    days: 'Любой день',
    daysKey: 'any',
    price: 'Индивидуально',
    priceKey: 'negotiable',
    location: 'both',
    durationKey: 'negotiable',
    desc: 'Мероприятия — это организация праздников любого формата: дни рождения, свидания в мастерской, корпоративы, девичники и аренда зала на ВДНХ. Опытные мастера обучают гончарному ремеслу, ручной лепке и росписи, помогая создать авторское изделие. Подходит для детей от 3 лет и взрослых.',
    cta: { label: 'Подробнее', variant: 'outline' as const, icon: 'ArrowRight' },
  },
  {
    img: 'https://cdn.poehali.dev/projects/b241161a-f0d6-42a2-9d30-83e375a0753b/bucket/7f664b40-fac2-4114-b0ad-70fc8524f908.png',
    icon: 'Truck',
    title: 'Выездной мастер-класс',
    place: 'Выезд к вам',
    duration: 'от 30 мин',
    people: '1–100',
    peopleMin: 1,
    peopleMax: 100,
    age: '3+',
    ageMin: 3,
    days: 'Любой день',
    daysKey: 'any',
    price: 'Договорная',
    priceKey: 'negotiable',
    location: 'offsite',
    durationKey: 'negotiable',
    desc: 'Выездной мастер-класс, куда входит лепка из глины, роспись ангобами и акрилом. Мастера приезжают с материалами и инструментами, подходит для детей и взрослых, готовые изделия забираете с собой. Стоимость рассчитывается индивидуально.',
    cta: { label: 'Отправить заявку', variant: 'outline' as const, icon: 'Send', action: 'offsite' },
  },
];

export type FormatItem = (typeof ALL_FORMATS)[number];

export const AGE_OPTIONS = ['3+', '7+', '10+', '12+'];
export const DAY_OPTIONS = [
  { label: 'Любой', value: 'any' },
  { label: 'Пн–Пт', value: 'weekday' },
  { label: 'Сб/Вс', value: 'weekend' },
];
export const DURATION_OPTIONS = [
  { label: '1 час', value: '1h' },
  { label: '6+ ч', value: '6h' },
  { label: 'Договорная', value: 'negotiable' },
];
export const LOCATION_OPTIONS = [
  { label: 'Любой', value: 'any' },
  { label: 'В студии', value: 'studio' },
  { label: 'Выезд', value: 'offsite' },
];
export const PEOPLE_OPTIONS = [
  { label: 'До 10', value: 'lt10', min: 1, max: 9 },
  { label: 'От 10 до 20', value: '10-20', min: 10, max: 20 },
  { label: 'От 20 до 30', value: '20-30', min: 20, max: 30 },
];